title: gr.gro
description: De tudo um pouco

url: https://github.com/gregribo/gr.io
baseurl: ""
paginate_path: "posts/pag:num/"
permalink: :categories/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Concursos Î¨
   url: /concursos
 - title: Blog
   url: /blog
 - title: Sobre
   url: /sobre
# - title: Contato
#   url: /contact

social:
   github: gregribo
   twitter: gregribo	
   facebook: gregrorio.masildi
   email: gribmir@gmail.com

google_analytics: "UA-58263416-1"
