title: GGio - Psicologia para concurso e blog do Gregório
description: Aulas e resumos de psicologia para concursos públicos e blog pessoal do Gregório.
mini-title: GGio - Psicologia para concurso

url: "http://ggio.com.br"
baseurl: ""
paginate_path: "posts/pag:num/"
permalink: :categories/:title/

markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
highlighter: pygments
paginate: 5

navigation:
 - title: <i class="fa fa-book fa-lg"></i>&nbsp; Psicologia para concurso
   url: /psicologia-para-concurso
 - title: <i class="fa fa-pencil fa-lg"></i>&nbsp; Blog
   url: /blog
 - title: <i class="fa fa-user fa-lg"></i>&nbsp; Sobre
   url: /sobre

social:
   github: ggio
   twitter: gregribo	
   facebook: gregrorio.masildi
   email: gribmir@gmail.com

# google_analytics: "UA-58263416-1"
